### ISSUE TITLE
canyougiveme the whole  project with pbc 

### ISSUE THREAD

**Issue by baozi78** [atulmahind/PEKS#1]

**Comment by baozi78** [comment]
my email is bao_zijian@163.com    thankyou for your work. i cant run the project with the pbc library in 
VC.there is a lot of bugs.i dont why.can you send me the whole project wtih pbc ?

**Comment by atulmahind** [comment]
The project was developed in Ubuntu 14.04 and I have updated the environment so, can't really help you with that. If you can share the errors may be we can find the way.

**Comment by baozi78** [comment]
i have slove this problem tonight. there is no mistake in your work.recently .i have read some paper by dan boneh about seachable encryption. I want to continue working on the basis of your work.  thank for your work.

**Comment by atulmahind** [comment]
You are always welcome. Good luck with your work!
