### ISSUE TITLE
peks.c file

### ISSUE THREAD

**Issue by abhinabbishoyi** [atulmahind/PEKS#2]
brother how can i also see print statements of peks.c file
rightnow only main.c file print statement is working

**Comment by atulmahind** [comment]
@abhinabbishoyi I hope you have solved this issue by now.

Hint: You can enable DEBUG logs in [main.c](https://github.com/atulmahind/PEKS/blob/086f839d77975963a4179d4d375f4ffc91eefa69/main.c#L12).
